export const FETCH_ALL_PROCCESS = "FETCH_ALL_PROCCESS";
export const FETCH_PROCCESS = "FETCH_PROCCESS";
export const ADD_PROCCESS = "ADD_PROCCESS";
export const DELETE_PROCCESS = "DELETE_PROCCESS";
export const UPDATE_PROCCESS = "DELETE_PROCCESS";
