export const FETCH_GROUP_RIGHTS = "FETCH_GROUP_RIGHTS";
export const FETCH_GROUP_RIGHT = "FETCH_GROUP_RIGHT";
export const ADD_GROUP_RIGHT = "ADD_GROUP_RIGHT";
export const DELETE_GROUP_RIGHT = "DELETE_GROUP_RIGHT";
export const UPDATE_GROUP_RIGHT = "UPDATE_GROUP_RIGHT";
