export const FETCH_ORGANIZATIONAL_STRUCTURE = "FETCH_ORGANIZATIONAL_STRUCTURE";
export const FETCH_ORGANIZATIONAL_INFO = "FETCH_ORGANIZATIONAL_INFO";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const ADD_AFFILIATED_DEPARTMENT = "ADD_AFFILIATED_DEPARTMENT";
export const DELETE_AFFILIATED_DEPARTMENT = "DELETE_AFFILIATED_DEPARTMENT";
