export const FETCH_ORGANIZATIONAL = "FETCH_ORGANIZATIONAL";
export const FETCH_DEPARTMENTS = "FETCH_DEPARTMENTS";
export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
