export const FETCH_ALL_ASSIGNED = "FETCH_ALL_ASSIGNED";
export const FETCH_ASSIGNED = "FETCH_ASSIGNED";
export const ADD_ASSIGNED = "ADD_ASSIGNED";
export const DELETE_ASSIGNED = "DELETE_ASSIGNED";
export const UPDATE_ASSIGNED = "UPDATE_ASSIGNED";
