export const FETCH_SENDERS = "FETCH_SENDERS";
export const FETCH_SENDER = "FETCH_SENDER";
export const ADD_SENDER = "ADD_SENDER";
export const DELETE_SENDER = "DELETE_SENDER";
export const UPDATE_SENDER = "DELETE_SENDER";
